namespace DST.Models.BusinessLogic
{
    public enum TrackSummaryItem
    {
        RightAscension,
        Declination,
        Catalog,
        Type,
        Description,
        Constellation,
        Distance,
        Magnitude,
        Season,
        Latitude,
        Longitude,
        TimeZone,
        LocalTime,
        UniversalTime,
        Algorithm,
        TimeKeeper,
        LocalTimeKeeper,
        LocalHourAngle,
        EquationOfEquinoxes,
        EquationOfOrigins,
        Altitude,
        Azimuth,
        Trajectory,
        Visibility
    }
}
