//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DST.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DST.Core.Resources.DisplayText", typeof(DisplayText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth Rotation Angle.
        /// </summary>
        public static string AlgorithmERALong {
            get {
                return ResourceManager.GetString("AlgorithmERALong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERA.
        /// </summary>
        public static string AlgorithmERAShort {
            get {
                return ResourceManager.GetString("AlgorithmERAShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenwich Apparent Sidereal Time.
        /// </summary>
        public static string AlgorithmGASTLong {
            get {
                return ResourceManager.GetString("AlgorithmGASTLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAST.
        /// </summary>
        public static string AlgorithmGASTShort {
            get {
                return ResourceManager.GetString("AlgorithmGASTShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenwich Mean Sidereal Time.
        /// </summary>
        public static string AlgorithmGMSTLong {
            get {
                return ResourceManager.GetString("AlgorithmGMSTLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMST.
        /// </summary>
        public static string AlgorithmGMSTShort {
            get {
                return ResourceManager.GetString("AlgorithmGMSTShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apex.
        /// </summary>
        public static string AltitudeApex {
            get {
                return ResourceManager.GetString("AltitudeApex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise.
        /// </summary>
        public static string AltitudeRise {
            get {
                return ResourceManager.GetString("AltitudeRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string AltitudeSet {
            get {
                return ResourceManager.GetString("AltitudeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidereal Time.
        /// </summary>
        public static string TimeScaleSidereal {
            get {
                return ResourceManager.GetString("TimeScaleSidereal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean Solar Time.
        /// </summary>
        public static string TimeScaleSolar {
            get {
                return ResourceManager.GetString("TimeScaleSolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellar Time.
        /// </summary>
        public static string TimeScaleStellar {
            get {
                return ResourceManager.GetString("TimeScaleStellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string TimeUnitDays {
            get {
                return ResourceManager.GetString("TimeUnitDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string TimeUnitHours {
            get {
                return ResourceManager.GetString("TimeUnitHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string TimeUnitMinutes {
            get {
                return ResourceManager.GetString("TimeUnitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string TimeUnitMonths {
            get {
                return ResourceManager.GetString("TimeUnitMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string TimeUnitSeconds {
            get {
                return ResourceManager.GetString("TimeUnitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        public static string TimeUnitWeeks {
            get {
                return ResourceManager.GetString("TimeUnitWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string TimeUnitYears {
            get {
                return ResourceManager.GetString("TimeUnitYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circumpolar.
        /// </summary>
        public static string TrajectoryCircumpolar {
            get {
                return ResourceManager.GetString("TrajectoryCircumpolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circumpolar Offset.
        /// </summary>
        public static string TrajectoryCircumpolarOffset {
            get {
                return ResourceManager.GetString("TrajectoryCircumpolarOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Rise.
        /// </summary>
        public static string TrajectoryNeverRise {
            get {
                return ResourceManager.GetString("TrajectoryNeverRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise and Set.
        /// </summary>
        public static string TrajectoryRiseAndSet {
            get {
                return ResourceManager.GetString("TrajectoryRiseAndSet", resourceCulture);
            }
        }
    }
}
