//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DST.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AngleFormats {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AngleFormats() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DST.Resources.AngleFormats", typeof(AngleFormats).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}E.
        /// </summary>
        public static string BearingFormatEast {
            get {
                return ResourceManager.GetString("BearingFormatEast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}N.
        /// </summary>
        public static string BearingFormatNorth {
            get {
                return ResourceManager.GetString("BearingFormatNorth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}S.
        /// </summary>
        public static string BearingFormatSouth {
            get {
                return ResourceManager.GetString("BearingFormatSouth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}W.
        /// </summary>
        public static string BearingFormatWest {
            get {
                return ResourceManager.GetString("BearingFormatWest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}°.
        /// </summary>
        public static string CompactFormatDegrees {
            get {
                return ResourceManager.GetString("CompactFormatDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}h.
        /// </summary>
        public static string CompactFormatHours {
            get {
                return ResourceManager.GetString("CompactFormatHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0}°{1:00}&apos;{2:00.###}&quot;.
        /// </summary>
        public static string ComponentFormatDegrees {
            get {
                return ResourceManager.GetString("ComponentFormatDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:00}h {1:00}m {2:00.###}s.
        /// </summary>
        public static string ComponentFormatHours {
            get {
                return ResourceManager.GetString("ComponentFormatHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string CoordinateFormatNoDelimiter {
            get {
                return ResourceManager.GetString("CoordinateFormatNoDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}, {1}.
        /// </summary>
        public static string CoordinateFormatWithDelimiter {
            get {
                return ResourceManager.GetString("CoordinateFormatWithDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.0###}°.
        /// </summary>
        public static string DecimalFormatDegrees {
            get {
                return ResourceManager.GetString("DecimalFormatDegrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:0.0###}h.
        /// </summary>
        public static string DecimalFormatHours {
            get {
                return ResourceManager.GetString("DecimalFormatHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -{0}.
        /// </summary>
        public static string SignedFormatNegativeValue {
            get {
                return ResourceManager.GetString("SignedFormatNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to +{0}.
        /// </summary>
        public static string SignedFormatPositiveValue {
            get {
                return ResourceManager.GetString("SignedFormatPositiveValue", resourceCulture);
            }
        }
    }
}
