//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DST.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DST.Resources.DisplayText", typeof(DisplayText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earth Rotation Angle.
        /// </summary>
        public static string AlgorithmERALong {
            get {
                return ResourceManager.GetString("AlgorithmERALong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERA.
        /// </summary>
        public static string AlgorithmERAShort {
            get {
                return ResourceManager.GetString("AlgorithmERAShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenwich Apparent Sidereal Time.
        /// </summary>
        public static string AlgorithmGASTLong {
            get {
                return ResourceManager.GetString("AlgorithmGASTLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GAST.
        /// </summary>
        public static string AlgorithmGASTShort {
            get {
                return ResourceManager.GetString("AlgorithmGASTShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenwich Mean Sidereal Time.
        /// </summary>
        public static string AlgorithmGMSTLong {
            get {
                return ResourceManager.GetString("AlgorithmGMSTLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GMST.
        /// </summary>
        public static string AlgorithmGMSTShort {
            get {
                return ResourceManager.GetString("AlgorithmGMSTShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apex.
        /// </summary>
        public static string AltitudeApex {
            get {
                return ResourceManager.GetString("AltitudeApex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise.
        /// </summary>
        public static string AltitudeRise {
            get {
                return ResourceManager.GetString("AltitudeRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        public static string AltitudeSet {
            get {
                return ResourceManager.GetString("AltitudeSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent Magnitude: none.
        /// </summary>
        public static string ApparentMagnitudeDefault {
            get {
                return ResourceManager.GetString("ApparentMagnitudeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apparent Magnitude: {0:0.0#}.
        /// </summary>
        public static string ApparentMagnitudeFormatDecimal {
            get {
                return ResourceManager.GetString("ApparentMagnitudeFormatDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:n} kly.
        /// </summary>
        public static string DistanceFormatDecimalKly {
            get {
                return ResourceManager.GetString("DistanceFormatDecimalKly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FilterAll {
            get {
                return ResourceManager.GetString("FilterAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catalog.
        /// </summary>
        public static string FilterCatalog {
            get {
                return ResourceManager.GetString("FilterCatalog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constellation.
        /// </summary>
        public static string FilterConstellation {
            get {
                return ResourceManager.GetString("FilterConstellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local.
        /// </summary>
        public static string FilterLocal {
            get {
                return ResourceManager.GetString("FilterLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string FilterName {
            get {
                return ResourceManager.GetString("FilterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string FilterOff {
            get {
                return ResourceManager.GetString("FilterOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string FilterOn {
            get {
                return ResourceManager.GetString("FilterOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rising.
        /// </summary>
        public static string FilterRising {
            get {
                return ResourceManager.GetString("FilterRising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string FilterSearch {
            get {
                return ResourceManager.GetString("FilterSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Season.
        /// </summary>
        public static string FilterSeason {
            get {
                return ResourceManager.GetString("FilterSeason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trajectory.
        /// </summary>
        public static string FilterTrajectory {
            get {
                return ResourceManager.GetString("FilterTrajectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string FilterType {
            get {
                return ResourceManager.GetString("FilterType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string FilterUnknown {
            get {
                return ResourceManager.GetString("FilterUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visible.
        /// </summary>
        public static string FilterVisible {
            get {
                return ResourceManager.GetString("FilterVisible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude must be in the range from -90.0 to 90.0.
        /// </summary>
        public static string LatitudeValidationMessage {
            get {
                return ResourceManager.GetString("LatitudeValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude must be in the range from -180.0 to 180.0.
        /// </summary>
        public static string LongitudeValidationMessage {
            get {
                return ResourceManager.GetString("LongitudeValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} results.
        /// </summary>
        public static string PageResultsFormatMultiple {
            get {
                return ResourceManager.GetString("PageResultsFormatMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-{1} of {2} results.
        /// </summary>
        public static string PageResultsFormatRange {
            get {
                return ResourceManager.GetString("PageResultsFormatRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 result.
        /// </summary>
        public static string PageResultsFormatSingle {
            get {
                return ResourceManager.GetString("PageResultsFormatSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} per page.
        /// </summary>
        public static string PageSizeFormat {
            get {
                return ResourceManager.GetString("PageSizeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise time not available.
        /// </summary>
        public static string RiseTimeDefault {
            get {
                return ResourceManager.GetString("RiseTimeDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0} hr.
        /// </summary>
        public static string RiseTimeFormatHoursFuture {
            get {
                return ResourceManager.GetString("RiseTimeFormatHoursFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:F0} hr ago.
        /// </summary>
        public static string RiseTimeFormatHoursPast {
            get {
                return ResourceManager.GetString("RiseTimeFormatHoursPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min.
        /// </summary>
        public static string RiseTimeFormatMinutesFuture {
            get {
                return ResourceManager.GetString("RiseTimeFormatMinutesFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} min ago.
        /// </summary>
        public static string RiseTimeFormatMinutesPast {
            get {
                return ResourceManager.GetString("RiseTimeFormatMinutesPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sec.
        /// </summary>
        public static string RiseTimeFormatSecondsFuture {
            get {
                return ResourceManager.GetString("RiseTimeFormatSecondsFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} sec ago.
        /// </summary>
        public static string RiseTimeFormatSecondsPast {
            get {
                return ResourceManager.GetString("RiseTimeFormatSecondsPast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 50 characters allowed.
        /// </summary>
        public static string SearchLengthValidationMessage {
            get {
                return ResourceManager.GetString("SearchLengthValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters are not allowed.
        /// </summary>
        public static string SearchRegexValidationMessage {
            get {
                return ResourceManager.GetString("SearchRegexValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The search input cannot be empty.
        /// </summary>
        public static string SearchRequiredValidationMessage {
            get {
                return ResourceManager.GetString("SearchRequiredValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asc.
        /// </summary>
        public static string SortAsc {
            get {
                return ResourceManager.GetString("SortAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ascending.
        /// </summary>
        public static string SortAscending {
            get {
                return ResourceManager.GetString("SortAscending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desc.
        /// </summary>
        public static string SortDesc {
            get {
                return ResourceManager.GetString("SortDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descending.
        /// </summary>
        public static string SortDescending {
            get {
                return ResourceManager.GetString("SortDescending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brightness.
        /// </summary>
        public static string SortFieldBrightness {
            get {
                return ResourceManager.GetString("SortFieldBrightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constellation.
        /// </summary>
        public static string SortFieldConstellation {
            get {
                return ResourceManager.GetString("SortFieldConstellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string SortFieldDistance {
            get {
                return ResourceManager.GetString("SortFieldDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id.
        /// </summary>
        public static string SortFieldId {
            get {
                return ResourceManager.GetString("SortFieldId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string SortFieldName {
            get {
                return ResourceManager.GetString("SortFieldName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise Time.
        /// </summary>
        public static string SortFieldRiseTime {
            get {
                return ResourceManager.GetString("SortFieldRiseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string SortFieldType {
            get {
                return ResourceManager.GetString("SortFieldType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sidereal Time.
        /// </summary>
        public static string TimeScaleSidereal {
            get {
                return ResourceManager.GetString("TimeScaleSidereal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean Solar Time.
        /// </summary>
        public static string TimeScaleSolar {
            get {
                return ResourceManager.GetString("TimeScaleSolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stellar Time.
        /// </summary>
        public static string TimeScaleStellar {
            get {
                return ResourceManager.GetString("TimeScaleStellar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days.
        /// </summary>
        public static string TimeUnitDays {
            get {
                return ResourceManager.GetString("TimeUnitDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string TimeUnitHours {
            get {
                return ResourceManager.GetString("TimeUnitHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string TimeUnitMinutes {
            get {
                return ResourceManager.GetString("TimeUnitMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Months.
        /// </summary>
        public static string TimeUnitMonths {
            get {
                return ResourceManager.GetString("TimeUnitMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds.
        /// </summary>
        public static string TimeUnitSeconds {
            get {
                return ResourceManager.GetString("TimeUnitSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weeks.
        /// </summary>
        public static string TimeUnitWeeks {
            get {
                return ResourceManager.GetString("TimeUnitWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years.
        /// </summary>
        public static string TimeUnitYears {
            get {
                return ResourceManager.GetString("TimeUnitYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circumpolar.
        /// </summary>
        public static string TrajectoryCircumpolar {
            get {
                return ResourceManager.GetString("TrajectoryCircumpolar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circumpolar Offset.
        /// </summary>
        public static string TrajectoryCircumpolarOffset {
            get {
                return ResourceManager.GetString("TrajectoryCircumpolarOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never Rise.
        /// </summary>
        public static string TrajectoryNeverRise {
            get {
                return ResourceManager.GetString("TrajectoryNeverRise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rise and Set.
        /// </summary>
        public static string TrajectoryRiseAndSet {
            get {
                return ResourceManager.GetString("TrajectoryRiseAndSet", resourceCulture);
            }
        }
    }
}
